// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1JeM0FVd6Y2YsQy-RvDZ_COYQ2pUdjVk',
    appId: '1:1015567449822:web:9299d50c59112f5b2e8c4f',
    messagingSenderId: '1015567449822',
    projectId: 'fire-emulator-demo',
    authDomain: 'fire-emulator-demo.firebaseapp.com',
    storageBucket: 'fire-emulator-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMMD3hQgeT-LYOwPFKm5oLik-7XBEeNsc',
    appId: '1:1015567449822:android:9ff96786ae27fa742e8c4f',
    messagingSenderId: '1015567449822',
    projectId: 'fire-emulator-demo',
    storageBucket: 'fire-emulator-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2zaE8Z9t68AAKqVp-oXgKjVmipd7tZBo',
    appId: '1:1015567449822:ios:003b020e5908989f2e8c4f',
    messagingSenderId: '1015567449822',
    projectId: 'fire-emulator-demo',
    storageBucket: 'fire-emulator-demo.appspot.com',
    iosClientId: '1015567449822-rsbh077b7lagaev58idsfai9ehl6t2p8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFireEmulator',
  );
}
